name: freezed_go_style
description: A Dart formatter that applies Go-style alignment to Freezed models, making your code more readable and consistent.
version: 1.0.1
homepage: https://github.com/Okladnoj/freezed_go_style
repository: https://github.com/Okladnoj/freezed_go_style
issue_tracker: https://github.com/Okladnoj/freezed_go_style/issues

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.7.0
  analyzer: '>=7.5.9 <10.0.0'
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
