name: freezed_go_style
description: Formatter for Freezed models in Go-style alignment.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.7.0
  analyzer: '>=7.5.9 <10.0.0'
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
