name: freezed_go_style
description: A Dart formatter that applies Go-style alignment to Freezed models, making your code more readable and consistent.
version: 1.0.4
homepage: https://github.com/Okladnoj/freezed_go_style
repository: https://github.com/Okladnoj/freezed_go_style
issue_tracker: https://github.com/Okladnoj/freezed_go_style/issues

screenshots:
  - description: "freezed go style formatter"
    path: ass/freezed_go_style-logo.png

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.7.0
  analyzer: '>=5.12.0 <10.0.0'
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

keywords:
  - dart
  - freezed
  - formatter
  - code-formatting
  - alignment
  - go-style

topics:
  - formatter
  - freezed
  - code-formatting
  - alignment
  - dart

executables:
  freezed_go_style: freezed_go_style

license: MIT
